POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content" : "VS Code Rest client is pretty good too", 
  "important": false
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  
  "important": true
}